name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  generate_index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install airium
        run: |
          pip install airium
          
      - name: Generate index.html
        run: |
          python generate_html.py
          
      - name: Archive generated index.html
        uses: actions/upload-artifact@v2
        with:
          name: Generated index.html
          path: generated_index.html
